/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wanaka' at '17/05/02 10:19' with Gradle 2.1
 *
 * @author wanaka, @date 17/05/02 10:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
